version: '3'
services:
  app:
    image: your_image_name
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    environment:
      - ENV_VARIABLE=value
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
